version: '3'
services:
  db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3305:3305"
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  redis:
        image: 'redis:5-alpine'
        restart: always
        ports:
            - "6379:6379"
  app: 
        build: .
        command: bash -c "bash ./init.sh"
        volumes: 
            - ".:/app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
            - redis
            - rabbitmq
            - elasticsearch
        restart: always
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: redis://localhost:6379/1
            RABBITMQ_HOST: rabbitmq
            ES_HOST: elasticsearch
  chatworker:
            build: .
            command: rake sneakers:run
            volumes:
              - .:/app
            depends_on:
              - db
              - rabbitmq
            restart: always
            environment:
              DB_USER: root
              DB_NAME: app
              DB_PASSWORD: password
              DB_HOST: db
              RABBITMQ_HOST: rabbitmq
              WORKERS: ChatWorker
  messageworker:
            build: .
            command: rake sneakers:run
            volumes:
              - .:/app
            depends_on:
              - db
              - rabbitmq
            restart: always
            environment:
              DB_USER: root
              DB_NAME: app
              DB_PASSWORD: password
              DB_HOST: db
              RABBITMQ_HOST: rabbitmq
              WORKERS: MessageWorker
              ES_HOST: elasticsearch
  elasticsearch:
        container_name: es-container
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
          - xpack.security.enabled=false
          - "discovery.type=single-node"
        ports:
          - 9200:9200
 
