version: '3'
services:
  rabbitmq:
      image: rabbitmq:3-management
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
      container_name: rabbitmq
      ports:
        - 15672:15672
        - 5671-5672:5671-5672
      restart: always
      labels:
        name:
          rabbitmq
  db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3305:3305"
  redis:
        image: 'redis:5-alpine'
        restart: always
        ports:
            - "6379:6379"
  elasticsearch:
        container_name: es-container
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
          - xpack.security.enabled=false
          - "discovery.type=single-node"
        ports:
          - 9200:9200
  
  app: 
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
            - redis
            - rabbitmq
            - elasticsearch
        links:
            - db
            - redis
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: redis://localhost:6379/1
            RABBITMQ_HOST: rabbitmq
            ES_HOST: elasticsearch
  sneakers:
        build: .
        volumes:
          - .:/app
        depends_on:
          - db
          - rabbitmq
          - app
          - redis

        links: 
          - rabbitmq 
        command: bash -c "bundle exec rake rabbitmq:setup && bundle exec rake sneakers:run"
        restart: on-failure
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: redis://localhost:6379/1
            RABBITMQ_HOST: rabbitmq
            ES_HOST: elasticsearch
